[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube

# build flags
build_flags = 
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    
# upload settings
upload_protocol = serial

# monitor settings  
monitor_speed = 115200